permissions:
  contents: read
  pages: write
  id-token: write

name: Docs

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: yarn install --immutable

      - name: Build
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn workspace docs run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './packages/docs/build/.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
