name: Run Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: 22
  BUILT_ARTIFACT_NAME: build-packages

jobs:
  install-deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        id: cache-key
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-v2-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-key.outputs.cache-hit != 'true'
        run: yarn install --immutable

  build:
    name: Build packages
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-v2-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Build scripts
        run: yarn build:scripts

      - name: Build packages
        run: yarn build

      - name: Upload built scripts and core
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILT_ARTIFACT_NAME }}
          path: |
            scripts/built
            packages/**/dist

  test:
    name: Run tests
    needs: [install-deps, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-v2-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILT_ARTIFACT_NAME }}

      - name: Run tests
        run: yarn test

  lint:
    name: Lint packages
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-v2-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Lint packages
        run: yarn lint

  type-check:
    name: Type-check packages
    needs: [install-deps, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-v2-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILT_ARTIFACT_NAME }}

      - name: Type-check packages
        run: yarn typecheck
