name: Run Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Prepare environment
        uses: ./.github/actions/prepare-rattus-env

      - name: Cache dependencies
        id: cache-key
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-key.outputs.cache-hit != 'true'
        run: yarn

  build-scripts:
    name: Build Rattus scripts
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        uses: ./.github/actions/prepare-rattus-env

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Build scripts
        run: yarn build:scripts

  test:
    name: Run tests
    needs: [install-deps, build-scripts]
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        uses: ./.github/actions/prepare-rattus-env

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Run tests
        run: yarn test

  build:
    name: Build packages
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        uses: ./.github/actions/prepare-rattus-env

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Build packages
        run: yarn build

  lint:
    name: Lint packages
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        uses: ./.github/actions/prepare-rattus-env

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Lint packages
        run: yarn lint

  type-check:
    name: Type-check packages
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        uses: ./.github/actions/prepare-rattus-env

      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Type-check packages
        run: yarn typecheck
